service: hemalytica-com-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'prod'}
  region: ap-south-1
  environment:
    WAITLIST_TABLE: ${opt:stage, 'prod'}-${self:service}-waitlist
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - !GetAtt WaitlistTable.Arn

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  individually: true

functions:
  addToWaitlist:
    handler: src/handlers/addToWaitlist.handler
    events:
      - http:
          path: waitlist
          method: post
          cors:
            origin: 'https://www.hemalytica.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true

resources:
  Resources:
    WaitlistTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.WAITLIST_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: createdOn
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: createdOn
            KeyType: RANGE

custom:
  serverless-offline:
    httpPort: 4000
